In [1]:
from jupyter_bioacoustic import BioacousticAnnotator, print_md
import pandas as pd
from IPython.display import Markdown, display
from pprint import pprint, pformat

---

# ANNOTATE

Annotation workflow: assign species and mark time/frequency regions. Arguments can be passed directly to the `BioacousticAnnotator`, however it is often much more convient to use configuration files.  Here, in addition to the annotation files, we have passed additional kwargs (annotator_name, annotation_date) which will be passed directly to the output data.

In [2]:
ba_annotate = BioacousticAnnotator(
    project='annotator_config/projects/simple_annotator.yaml',
    annotator_name='brookie',
    annotate_date=20260515
)

In [3]:
ba_annotate.open()

In [12]:
ba_annotate.configuration

{'capture': True,
 'description': {'title': 'Info',
  'text': '# Data Collection\n\nThis simple annotator allows the user to do time annotations on a given audio clip and label the species. Five different styles of time annotations are available:\n\n- `time_select`: marks a single instance in time, usually the beginnig or middle, of a given sound.\n- `start_end_time_select`: mark the start and end time of a given sound\n- `fixed_duration`: allows user to place region of fixed duration anywhere on the audio clip and record the start and end time. This is most useful when the annotator is specifically looking for clips of a certain time. the "fixed" duration can optionally be made adjustable.\n- `bounding_box`: allows the user to tightly annotate (stat/end_time, min/max_frequency) a single sound on an audio clip\n- `multibox`: similar to `bounding_box` but the user is able to draw (and label) multiple bounding-boxes on a single clip',
  'open': False},
 'capture_dir': 'spectrograms',
 'default_buffer': 0,
 'info_card_title': 'Model Prediction: [[common_name]]',
 'info_card_text': 'confidence: [[confidence]]',
 'display_columns': ['deployment_code',
  'recording_start_datetime',
  'confidence',
  'audio_url'],
 'data': {'path': 'data/detections.N-dse.csv', 'index_column': 'id'},
 'audio': {'column': 'audio_url'},
 'sort': 'confidence',
 'sort_order': 'desc',
 'project_name': 'Simple Annotator',
 'output': {'path': 'outputs/simple_annotator.csv',
  'index_column': 'detection_id'},
 'form_config': {'title': {'value': 'ANNOTATE', 'progress_tracker': True},
  'annotation': {'tools': [{'fixed_duration': {'min': 1,
      'step': 1,
      'max': 15,
      'initial_window': 1}},
    'time_select',
    'start_end_time_select',
    'bounding_box',
    'multibox'],
   'form': 'species_form'},
  'submission_buttons': {'line': True,
   'next': {'label': 'Skip', 'icon': True},
   'submit': {'label': 'Submit', 'icon': True}},
  'dynamic_forms': {'species_form': [{'text': {'value': 'brookie, please select a species from the list below'}},
    {'select': {'label': 'Species',
      'column': 'species',
      'required': True,
      'items': {'path': 'data/species_counts.N-dse.csv',
       'value': 'common_name',
       'filter_box': True,
       'custom_value': True,
       'not_available': 'Unknown'}}}]},
  '_fixed_kwargs': [{'fixed_value': {'column': 'annotator_name',
     'value': 'brookie'}},
   {'fixed_value': {'column': 'annotate_date', 'value': 20260515}}]}}

In [13]:
print_md('**Source Data**')
ba_annotate.source.sample(3)

**Source Data**

,id,audio_path,audio_uri,audio_uri_public,audio_url,common_name,confidence,deployment_code,deployment_placename,deployment_subproject,end_time,lat,lon,rank,recording_end_datetime,recording_id,recording_start_datetime,scientific_name,start_time
6007,6007,audio/samples/EDSA2_2023.20230524_000000.flac,s3://casoundhub/audio/cemaf-acoustics/EDSA2_20...,s3://dse-soundhub/public/audio/samples/EDSA2_2...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Tree Swallow,0.893719,STER1_2023,STER1,2023,17274.0,35.703898,-119.612402,1,2023-05-24T09:00:00,181,2023-05-24T00:00:00,Tachycineta bicolor,17271.0
445,445,audio/samples/AGCA3_2023.20230528_200000.flac,s3://casoundhub/audio/cemaf-acoustics/AGCA3_20...,s3://dse-soundhub/public/audio/samples/AGCA3_2...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Engine,0.696318,NSWA3_2023,NSWA3,2023,4662.0,38.215152,-122.357000,1,2023-05-28T23:59:00,44,2023-05-28T20:00:00,Engine,4659.0
5073,5073,audio/samples/CBER4_2023.20230513_000000.flac,s3://casoundhub/audio/sentinel-site-acoustics/...,s3://dse-soundhub/public/audio/samples/CBER4_2...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Rock Wren,0.714236,SFVWA3_2023,SFVWA3,2023,30759.0,33.158334,-116.566685,1,2023-05-13T09:00:00,1465,2023-05-13T00:00:00,Salpinctes obsoletus,30756.0

In [14]:
print_md('**Annotated Data**')
ba_annotate.output().sample(3)

**Annotated Data**

,species,detection_id,start_time,end_time,min_frequency,max_frequency,annotator_name,annotate_date
28,Lesser Spotted Woodpecker,48,1828.73,1829.99,440.7,2148.7,brookie,20260527.0
0,White-backed Woodpecker,0,4.51,5.85,199.5,6030.1,brookie,20260524.0
4,Eurasian Woodcock,4,118.08,119.75,288.1,3458.0,brookie,20260525.0

---

# REVIEW

Simple review workflow: confirm or reject model predictions

In [15]:
ba_review = BioacousticAnnotator('annotator_config/projects/simple_review.yaml')
ba_review.open()