In [1]:
from jupyter_bioacoustic import BioacousticAnnotator, print_md
import pandas as pd
from IPython.display import Markdown, display
from pprint import pprint, pformat

---

# ANNOTATE

Annotation workflow: assign species and mark time/frequency regions. Arguments can be passed directly to the `BioacousticAnnotator`, however it is often much more convient to use configuration files.  Here, in addition to the annotation files, we have passed additional kwargs (annotator_name, annotation_date) which will be passed directly to the output data.

In [2]:
ba_annotate = BioacousticAnnotator(
    project='annotator_config/projects/simple_annotator.yaml',
    annotator_name='brookie',
    annotate_date=20260515
)

In [3]:
ba_annotate.open()

In [16]:
print_md('**Source Data**')
ba_annotate.source.sample(3)

**Source Data**

,id,audio_path,audio_uri,audio_uri_public,audio_url,common_name,confidence,deployment_code,deployment_placename,deployment_subproject,end_time,lat,lon,rank,recording_end_datetime,recording_id,recording_start_datetime,scientific_name,start_time
7730,7730,audio/samples/SELER4_2023.20230512_000000.flac,s3://casoundhub/audio/sentinel-site-acoustics/...,s3://dse-soundhub/public/audio/samples/SELER4_...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Yellow-breasted Chat,0.553984,USRO4_2023,USRO4,2023,20790.0,38.490739,-122.587458,1,2023-05-12T09:00:00,2534,2023-05-12T00:00:00,Icteria virens,20787.0
6883,6883,audio/samples/EDSA2_2023.20230524_000000.flac,s3://casoundhub/audio/cemaf-acoustics/EDSA2_20...,s3://dse-soundhub/public/audio/samples/EDSA2_2...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Bewick's Wren,0.863201,STER1_2023,STER1,2023,30834.0,35.703898,-119.612402,1,2023-05-24T09:00:00,181,2023-05-24T00:00:00,Thryomanes bewickii,30831.0
2676,2676,audio/samples/ESNERR3_2023.20230518_000000.flac,s3://casoundhub/audio/sentinel-site-acoustics/...,s3://dse-soundhub/public/audio/samples/ESNERR3...,https://dse-soundhub.s3.us-west-2.amazonaws.co...,Spotted Towhee,0.994733,SFSB2_2023,SFSB2,2023,27630.0,37.782177,-122.147732,1,2023-05-18T09:00:00,1833,2023-05-18T00:00:00,Pipilo maculatus,27627.0

In [17]:
print_md('**Annotated Data**')
ba_annotate.output().sample(3)

**Annotated Data**

,species,detection_id,start_time,end_time,min_frequency,max_frequency,annotator_name,annotate_date
32,Wren-like Rushbird,52,3090.66,3092.82,139.6,5848.9,brookie,20260525
39,Engine,61,4393.39,4394.73,NaN,NaN,brookie,20260527
11,Black-headed Grosbeak,18,319.39,320.84,330.9,4920.0,brookie,20260523

---

# REVIEW

Simple review workflow: confirm or reject model predictions

In [18]:
ba_review = BioacousticAnnotator('annotator_config/projects/simple_review.yaml')
ba_review.open()